component_depth: 1
languages:
- name: javascript
  production:
    exclude:
      - /docs/.*
      - /guide/.*
      - /npm-packages/.*
      - /scripts/.*
      - /packages/*tests.js
  test:
    include:
      - /packages/*tests.js
